version: '3.5'

services:
  raices:
    build: app
    command: yarn start
    ports:
        - '3000:3000'
        - '3001:3001'
    volumes:
        - ./app:/home/app-user/app
        - /home/app-user/app/node_modules
    environment:
      NODE_ENV: development
