// contact
export const PUT_CONTACT_FORM = 'PUT_CONTACT_FORM'
export const PUT_CONTACT_FORM_SUCCESS = 'PUT_CONTACT_FORM_SUCCESS'
export const PUT_CONTACT_FORM_ERROR = 'PUT_CONTACT_FORM_ERROR'

// visibility
export const FOOTER_VISIBILITY = 'FOOTER_VISIBILITY'
